table HOLDING_new
	lineageTag: 077f3477-fe6d-4cc6-9163-c797b6d13bf1

	column 'Period End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ba44a9ca-026b-4103-87fd-53b853e6e2c6
		summarizeBy: none
		sourceColumn: Period End Date

		variation Variation
			isDefault
			relationship: c05617cb-3741-4974-b3a0-54d73927335d
			defaultHierarchy: LocalDateTable_2316ac85-319d-46f1-8721-d7275513d201.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SOURCE_SYSTEM_CODE
		dataType: string
		lineageTag: 1bdabb89-52ce-4150-9c00-b313334afc90
		summarizeBy: none
		sourceColumn: SOURCE_SYSTEM_CODE

		annotation SummarizationSetBy = Automatic

	column SOURCE_SYSTEM_SHORT_NAME
		dataType: string
		lineageTag: a75a7088-036f-460c-b974-b20eafc0173d
		summarizeBy: none
		sourceColumn: SOURCE_SYSTEM_SHORT_NAME

		annotation SummarizationSetBy = Automatic

	column SOURCE_SYSTEM_NAME
		dataType: string
		lineageTag: 436d26a1-6c5d-42b9-b435-0bbb0a2484a2
		summarizeBy: none
		sourceColumn: SOURCE_SYSTEM_NAME

		annotation SummarizationSetBy = Automatic

	column PORTFOLIO_IDENTIFIER
		dataType: string
		lineageTag: b29e85f0-5c43-4e51-94e7-8c85fb735526
		summarizeBy: none
		sourceColumn: PORTFOLIO_IDENTIFIER

		annotation SummarizationSetBy = Automatic

	column 'Instrument Identifier'
		dataType: string
		lineageTag: 29bf55e6-efb9-403e-a096-5534246ca443
		summarizeBy: none
		sourceColumn: Instrument Identifier

		annotation SummarizationSetBy = Automatic

	column CUSTODIAN_ACCOUNT_IDENTIFIER
		dataType: string
		lineageTag: 0dad08a7-d3fd-47ec-8092-0005d73f91f8
		summarizeBy: none
		sourceColumn: CUSTODIAN_ACCOUNT_IDENTIFIER

		annotation SummarizationSetBy = Automatic

	column 'Position Quantity'
		dataType: double
		lineageTag: 4d17c234-5e10-4f64-b775-d3d90c990205
		summarizeBy: sum
		sourceColumn: Position Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ORIGINAL_FACE_AMOUNT
		dataType: double
		lineageTag: 66fb99da-ad7a-49b0-ba98-65b8d8dd0177
		summarizeBy: sum
		sourceColumn: ORIGINAL_FACE_AMOUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CURRENT_FACE_AMOUNT
		dataType: double
		lineageTag: b5c69d37-76fd-41d2-b22f-33d2002c4112
		summarizeBy: sum
		sourceColumn: CURRENT_FACE_AMOUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'MV Home Amount'
		dataType: double
		lineageTag: ce31dae9-48e4-4601-8861-1f190d564ba4
		summarizeBy: sum
		sourceColumn: MV Home Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MV_LOCAL_AMOUNT
		dataType: double
		lineageTag: 7feb1ff8-ddbe-4d7a-b389-eeb3fa1570a7
		summarizeBy: sum
		sourceColumn: MV_LOCAL_AMOUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Accrued
		dataType: double
		lineageTag: f86f0c2f-cba3-48fb-8b35-fd6b6e43cfb8
		summarizeBy: sum
		sourceColumn: Accrued

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ACCRUED_LOCAL_AMOUNT
		dataType: double
		lineageTag: 777cea7c-a2d6-4bd2-961b-519babef262d
		summarizeBy: sum
		sourceColumn: ACCRUED_LOCAL_AMOUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COST_BASIS_HOME_AMOUNT
		dataType: double
		lineageTag: 9752c63c-9b2a-4d75-a0aa-a8ce521cd10d
		summarizeBy: sum
		sourceColumn: COST_BASIS_HOME_AMOUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COST_BASIS_LOCAL_AMOUNT
		dataType: double
		lineageTag: 0d3156ad-49c0-4499-a8e4-78e828adeb19
		summarizeBy: sum
		sourceColumn: COST_BASIS_LOCAL_AMOUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CURRENCY_CODE
		dataType: string
		lineageTag: c0d203b9-a940-4d7a-ac8e-c028bdb477f7
		summarizeBy: none
		sourceColumn: CURRENCY_CODE

		annotation SummarizationSetBy = Automatic

	column PRICE_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 48256b41-ae04-4fae-bf31-72fd50549b28
		summarizeBy: none
		sourceColumn: PRICE_DATE

		variation Variation
			isDefault
			relationship: a99c54b6-0e9f-4e59-9705-a8ea9527a970
			defaultHierarchy: LocalDateTable_fafeed5c-9a2a-4e42-8c81-006e8704ba91.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Price Home Amount'
		dataType: double
		lineageTag: 4d1e36a6-61f2-4ca7-8686-d1dcee0f642d
		summarizeBy: sum
		sourceColumn: Price Home Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PRICE_LOCAL_AMOUNT
		dataType: double
		lineageTag: ad959e20-81c9-454c-adcf-f754ebe4675a
		summarizeBy: sum
		sourceColumn: PRICE_LOCAL_AMOUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PRICE_SOURCE_NAME
		dataType: string
		lineageTag: a779b066-2176-4a5f-8419-4ebf6fc7330b
		summarizeBy: none
		sourceColumn: PRICE_SOURCE_NAME

		annotation SummarizationSetBy = Automatic

	column 'FX Rate'
		dataType: double
		lineageTag: 41c984ef-485e-46d2-8677-2fa687176bfb
		summarizeBy: sum
		sourceColumn: FX Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Portfolio Holding Percent'
		dataType: double
		lineageTag: 9fdadc8b-bafd-4c76-bf19-f130ff0d0140
		summarizeBy: sum
		sourceColumn: Portfolio Holding Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REDEMPTION_FACTOR
		dataType: double
		lineageTag: deb93038-991b-43d2-b7ea-45b8d630d286
		summarizeBy: sum
		sourceColumn: REDEMPTION_FACTOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BASE_MARKET_VALUE
		dataType: double
		lineageTag: 7a2be774-18c7-4dc9-a72b-7cad910f9899
		summarizeBy: sum
		sourceColumn: BASE_MARKET_VALUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SOURCE_SYSTEM_STATUS_IDENTIFIER
		dataType: double
		lineageTag: 8ba0e26a-9733-49ef-9ed4-0cd10757a467
		summarizeBy: sum
		sourceColumn: SOURCE_SYSTEM_STATUS_IDENTIFIER

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ENDING_NAV_AMOUNT
		dataType: double
		lineageTag: 7221f014-c68d-4f22-8559-2d413ab0e31b
		summarizeBy: sum
		sourceColumn: ENDING_NAV_AMOUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BEGINNING_NAV_AMOUNT
		dataType: double
		lineageTag: 26874f1d-0442-4467-b4b7-df34b4eb246f
		summarizeBy: sum
		sourceColumn: BEGINNING_NAV_AMOUNT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SENTRY_PORTFOLIO_IDENTIFIER
		dataType: string
		lineageTag: 195f10a7-e4ad-4cb9-9208-0a4ef47dfd87
		summarizeBy: none
		sourceColumn: SENTRY_PORTFOLIO_IDENTIFIER

		annotation SummarizationSetBy = Automatic

	column POSITION_SETTLED_QUANTITY
		dataType: double
		lineageTag: 382c126b-6f2d-4f30-99c6-6036d6443ad6
		summarizeBy: sum
		sourceColumn: POSITION_SETTLED_QUANTITY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UNFUNDED_COMMITMENT_LOCAL
		dataType: double
		lineageTag: 531d87c5-812c-49bd-8347-308bd0b92078
		summarizeBy: sum
		sourceColumn: UNFUNDED_COMMITMENT_LOCAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DATA_PROVIDER_NAME
		dataType: string
		lineageTag: 6c6a4f57-37bd-4c74-83c3-0b85ee22ae9d
		summarizeBy: none
		sourceColumn: DATA_PROVIDER_NAME

		annotation SummarizationSetBy = Automatic

	column VANTAGE_PORTFOLIO_IDENTIFIER
		dataType: string
		lineageTag: dffb58e1-524e-4c5e-9c59-def3873d6b0d
		summarizeBy: none
		sourceColumn: VANTAGE_PORTFOLIO_IDENTIFIER

		annotation SummarizationSetBy = Automatic

	column VANTAGE_CUSTODIAN_ACCOUNT_IDENTIFIER
		dataType: string
		lineageTag: f7917c2f-fd1f-403a-99bb-4e44afd6e82a
		summarizeBy: none
		sourceColumn: VANTAGE_CUSTODIAN_ACCOUNT_IDENTIFIER

		annotation SummarizationSetBy = Automatic

	column CREATED_DATETIME
		dataType: dateTime
		formatString: General Date
		lineageTag: 4dd08aac-8122-4ff5-9237-c1dd81e214f1
		summarizeBy: none
		sourceColumn: CREATED_DATETIME

		variation Variation
			isDefault
			relationship: 2e04ab10-c892-4528-bd9d-0f8c7242c275
			defaultHierarchy: LocalDateTable_4c6e04ec-d91a-4ddb-bd8e-63dfa9fd7620.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column CREATED_BY_NAME
		dataType: string
		lineageTag: 5e566ada-2291-436a-9bbe-f5f3df7ac040
		summarizeBy: none
		sourceColumn: CREATED_BY_NAME

		annotation SummarizationSetBy = Automatic

	column CREATED_BY_COMMENTS
		dataType: string
		lineageTag: 645b6101-0f51-45e9-aa40-2ca3d69b95ff
		summarizeBy: none
		sourceColumn: CREATED_BY_COMMENTS

		annotation SummarizationSetBy = Automatic

	column MODIFIED_DATETIME
		dataType: dateTime
		formatString: General Date
		lineageTag: de94436c-26f6-43ec-9521-6b50f2aeb032
		summarizeBy: none
		sourceColumn: MODIFIED_DATETIME

		variation Variation
			isDefault
			relationship: 1e19110f-f3be-4e1b-bfe6-763f598d13e6
			defaultHierarchy: LocalDateTable_87560acd-9345-46b1-9487-74490bba1e2d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column MODIFIED_BY_NAME
		dataType: string
		lineageTag: f3adc4dd-55b8-4775-b893-7c2995180d8d
		summarizeBy: none
		sourceColumn: MODIFIED_BY_NAME

		annotation SummarizationSetBy = Automatic

	column MODIFIED_BY_COMMENTS
		dataType: string
		lineageTag: 7b23bc40-c5ab-4bba-998b-fe8e8a9628ef
		summarizeBy: none
		sourceColumn: MODIFIED_BY_COMMENTS

		annotation SummarizationSetBy = Automatic

	column ID_DATE
		dataType: string
		lineageTag: bb727721-2545-4c49-8d24-7879cdf3cc2b
		summarizeBy: none
		sourceColumn: ID_DATE

		annotation SummarizationSetBy = Automatic

	column ID_DATE_PORT
		dataType: string
		lineageTag: 0b3e41b4-3c53-426c-b600-c3a62db2e4b0
		summarizeBy: none
		sourceColumn: ID_DATE_PORT

		annotation SummarizationSetBy = Automatic

	partition HOLDING_new = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases(snowflake_url,"ANALYST_WH_XS"),
				    HUB_Database = Source{[Name="HUB",Kind="Database"]}[Data],
				    POSITION_Schema = HUB_Database{[Name="POSITION",Kind="Schema"]}[Data],
				    HOLDING_View = POSITION_Schema{[Name="HOLDING_DAILY",Kind="View"]}[Data],
				    #"Added Custom" = Table.AddColumn(HOLDING_View, "ID_DATE", each [INSTRUMENT_IDENTIFIER]&Date.ToText([PERIOD_END_DATE], [Format="yyyy-MM-dd"])),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Custom",{{"MV_HOME_AMOUNT", "MV Home Amount"}, {"PERIOD_END_DATE", "Period End Date"}, {"INSTRUMENT_IDENTIFIER", "Instrument Identifier"}, {"FX_RATE", "FX Rate"}, {"PORTFOLIO_HOLDING_PERCENT", "Portfolio Holding Percent"}, {"POSITION_QUANTITY", "Position Quantity"}, {"PRICE_HOME_AMOUNT", "Price Home Amount"}}),
				    #"Added Custom1" = Table.AddColumn(#"Renamed Columns", "ID_DATE_PORT", each [Instrument Identifier]&Date.ToText([Period End Date], [Format="yyyy-MM-dd"])&[PORTFOLIO_IDENTIFIER]),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Custom1",{{"ACCRUED_HOME_AMOUNT", "Accrued"}})
				in
				    #"Renamed Columns1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

